### ISSUE TITLE
Header-Bild & Format

### ISSUE THREAD

**Issue by signalwerk** [logrinto/website#10]
@marc-hatt 
ich habe mir erlaubt den url noch zu vereinheitlichen: https://github.com/logrinto/website/commit/6a4f7263d92a4cdb43159ac8c6b15cb74e1253a7

kannst du bitte bei deinem artikel noch folgende dinge ergänzen:
* [x] Header-Bild 
* [x] Bildquelle für Header-Bild am ende des Artikels vermerken (keine gestohlenen Bilder. Nur legale Inhalte)
* [x] Bei Recherche korrekte Links setzen mit Aufzählung

## nicht
[carsten-protsch.de](http://carsten-protsch.de/zwischennetz/doctype/prozent.html)

[thestyleworks.de](http://www.thestyleworks.de/basics/percentage.shtml)

...

## sondern
* [Browser ignorieren Prozentangaben für height · Carsten Protsch](http://carsten-protsch.de/zwischennetz/doctype/prozent.html) 
* ...

**Comment by marc-hatt** [comment]
Sollte alles soweit erledigt sein
