### ISSUE TITLE
Bildrechte & Quellen

### ISSUE THREAD

**Issue by signalwerk** [logrinto/website#11]
@severinkilchhofer @pascaleva @niciwatri 
ich habe mir erlaubt den url noch zu vereinheitlichen:
https://github.com/logrinto/website/commit/dc93fb25292a62d546368fd38212fba32ba98c53

* [x] Bildquelle für Header-Bild am ende des Artikels vermerken (keine gestohlenen Bilder. Nur legale Inhalte)
* [x] Die Bilder mit quellen sind auch copyright frei? nur weil die quelle da steht, dar man die nicht kopieren. ausser der autor/die autorin haben das frei gegeben.
* [x] Bei Quellen korrekte Links setzen

## nicht
* [carsten-protsch.de](http://carsten-protsch.de/zwischennetz/doctype/prozent.html)
* [thestyleworks.de](http://www.thestyleworks.de/basics/percentage.shtml)
* ...

## sondern
* [Browser ignorieren Prozentangaben für height · Carsten Protsch](http://carsten-protsch.de/zwischennetz/doctype/prozent.html) 
* ...

**Comment by niciwatri** [comment]
@signalwerk 
Hallo Stefan
– Das Headerbild habe ich selbst kreiert. Habe dies nun so vermerkt
– Bei den Bildern ist mir nicht klar, ob diese copyright frei sind. Ich finde nichts auf den jeweiligen Websites.
– Ich schaffe es nicht in diesem File die Quellen richtig als Links zu setzten. Mir ist nicht klar, ob ich es als HTMl oder MD setzen muss. Beides habe ich ausprobiert und klappt leider nicht...

**Comment by signalwerk** [comment]
@niciwatri 
* Headerbild → tiptop
* Bilder → wenn du nicht die Autorin bist und keine Lizenz beim Bild vermerkt ist, so musst du vom Standard ausgehen (also Urheberrechtlich geschützt) und darfst das Bild nicht verwenden.
*  Du kannst normale MD-Links setzten: `[Text des Links](https://domain.com/pfad/zum/inhalt/)` siehe auch [Spec](https://daringfireball.net/projects/markdown/syntax#link)
