### ISSUE TITLE
Copyright & Aufzählung

### ISSUE THREAD

**Issue by signalwerk** [logrinto/website#3]
@matthiasmeierkoch 
ich habe mir erlaubt den url noch zu vereinheitlichen: 
https://github.com/logrinto/website/commit/528d979a01401c563b739c730bb3910be3f535ae

kannst du bitte bei deinem artikel noch folgende dinge ergänzen:
* [x] Bildquelle für Header-Bild am ende des Artikels vermerken (keine gestohlenen Bilder. Nur legale Inhalte)
* [x] Du hast jetzt zwei H1 titel und zwei Leads in deinem Text. Kann man das vielleicht anders machen? Dein Titel (Zeile 2 im .md) könnte doch «WTF? What The Font(scale)» sein?
* [x] Bei Quellen korrekte Links setzen

## nicht
* [carsten-protsch.de](http://carsten-protsch.de/zwischennetz/doctype/prozent.html)
* [thestyleworks.de](http://www.thestyleworks.de/basics/percentage.shtml)
* ...

## sondern
* [Browser ignorieren Prozentangaben für height · Carsten Protsch](http://carsten-protsch.de/zwischennetz/doctype/prozent.html) 
* ...

**Comment by matthiasmeierkoch** [comment]
Änderungen gepusht, ok so?

**Comment by signalwerk** [comment]
@matthiasmeierkoch das schaut doch gut. aus. danke für die korrekturen!
