### ISSUE TITLE
Copyright

### ISSUE THREAD

**Issue by signalwerk** [logrinto/website#4]
@wschoeck @pascaleva @mariusbecker 
ich habe mir erlaubt den url noch zu vereinheitlichen: 
https://github.com/logrinto/website/commit/1a0a407999c477d8387468413a0658f6923c7172
Zudem habe ich die Autoren wie in allen Artikeln nur oben genannt und im Text entfernt.

Sind dies Bilder von Euch? keine copyrights darauf?

**Comment by pascaleva** [comment]
@signalwerk die Bilder sind alle von uns erstellt worden.

**Comment by signalwerk** [comment]
perfekt merci!
