### ISSUE TITLE
Copyright

### ISSUE THREAD

**Issue by signalwerk** [logrinto/website#5]
@larsmaeder 
ich habe mir erlaubt den url noch zu vereinheitlichen: 
https://github.com/logrinto/website/commit/b1b5a3499b891a244e53b308e28373e250da7ccc

Sind alle Bilder urheberrechtlich korrekt abgeklärt? Oder machen wir uns **strafbar**? Das Urheberrechtsgesetz gilt immer. Nur weil etwas im Netz ist, ist es noch lange nicht frei. Auch eine Quellenangabe reicht nicht, wenn es um Urheberrechtlich geschütztes Material geht. Dokumentieren einer bestehenden Website/Verhalten würde ich aber als unbedenklich empfinden. 

Bildquelle für Header-Bild am ende des Artikels vermerken (keine gestohlenen Bilder. Nur legale Inhalte)

**Comment by larsmaeder** [comment]
**Headerbild:**
https://unsplash.com/license
Even though **credit isn't required**, Unsplash photographers appreciate a credit as it provides exposure to their work and encourages them to continue sharing. A credit can be as simple as adding their name with a link to their profile or photo.

Urheberrecht der restlichen Bildern liegt bei mir.
