### ISSUE TITLE
Rechte & Autoren

### ISSUE THREAD

**Issue by signalwerk** [logrinto/website#6]
@stfffchs @NMA93 @matthiasmeierkoch 
ich habe mir erlaubt den url noch zu vereinheitlichen: 
https://github.com/logrinto/website/commit/9ce72ac8479649447c3fe2f8a6e0b611ceec355f

Als Autorin war nur Steffi vermerkt aber unten gab es eine Zusatzzeile mit drei Personen. Ich habe nun alle vermerkt. 

Sind alle Bilder urheberrechtlich korrekt abgeklärt? Oder machen wir uns **strafbar**? Das Urheberrechtsgesetz gilt immer. Nur weil etwas im Netz ist, ist es noch lange nicht frei. Auch eine Quellenangabe reicht nicht, wenn es um Urheberrechtlich geschütztes Material geht. Dokumentieren einer bestehenden Website/Verhalten würde ich aber als unbedenklich empfinden.

**Comment by stfffchs** [comment]
Hoi Stefan, das mit den Autoren betrifft alle Artikel. Jeder Artikel entstand aus einer Gruppenarbeit und jeder Artikel wurde von einer Einzelperson überarbeitet. Das müsste dann einfach überall gleich sein?

Das mit den Bildern schaue ich mir an.

**Comment by signalwerk** [comment]
@stfffchs soweit ich das sehe, wurden immer alle atoren angegeben. aber ich werde da boris noch einmal darauf ansetzen das zu prüfen. merci für die klärenden worte.
